### PR TITLE
Added skill/weapon modifier based on currentWounds

### PR DESCRIPTION
**Pull request by SkyJedi**
This should correctly modify the minion groups skills based on how many are alive

### CODE REVIEW

**Review by stoogoff — CHANGES_REQUESTED** [review]
I've taken a look at the code and I really like what you've done here! I've got a couple of issues with it which will need to be fixed before I put it live. The first one is straightforward the second may be more tricky and I'm open to any alternate solutions you may have for it.

1. The maths for calculating the number of living minions is repeated in two places across two components - this isn't ideal as it means changing this would require tracking it down in the code. This would be better handled in `character.jsx` and passed as props to `weapons-panel.jsx` and `skill-panel.jsx`.

2. The UI becomes inconsistent if you kill a minion and then adjust the number of minions. For example, if I create a squad of five stormtroopers the dice are correctly adjusted, wounds are set to the correct number and it says Roll (for 5) above the dice. If I enter 6 wounds in the current wounds box it adjusts the number of dice (which is awesome), the total wounds remain the same (I think this is the right way to handle that) but it still says Roll (for 5). If I reset the number of minions to one then add a minion the dice symbols don't adjust because it's still treating the first minion as being dead. I think the best thing to do here would be to reduce `currentWounds` to zero when the one button is pressed but, as I said, I'm open to suggestions.

Thanks for your work on this.

**Comment by SkyJedi** [comment]
easy peasy lemme know if my code still smells of a rotting fish :)

**Comment by stoogoff** [comment]
Perfect, thank you! I've merged the commit and I'm now going to push it live.

**Comment by SkyJedi** [comment]
Duuude sweet, swweeeeeet dude!  DUDE! SWEET!

**Pull request merged**
